{% set version = "7.2.0" %}

package:
  name: elasticsearch-dsl
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/elasticsearch-dsl/elasticsearch-dsl-{{ version }}.tar.gz
  sha256: 4015c0d25a0a5df05cf50fe7f3464234c5b97f050c85697399d96d46b30e09a7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - python-dateutil
    - elasticsearch >=7.0.0,<8.0.0
    - ipaddress  # [py<33]

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - elasticsearch_dsl

about:
  home: https://github.com/elasticsearch/elasticsearch-dsl-py
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Higher-level Python client for Elasticsearch
  dev_url: https://github.com/elasticsearch/elasticsearch-dsl-py
  doc_url: https://elasticsearch-dsl.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
