{% set version = "8.15.0" %}

package:
  name: elasticsearch-dsl
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/elasticsearch_dsl/elasticsearch_dsl-{{ version }}.tar.gz
  sha256: 9ffadfb48834d4562796b3c3e7d2da19fc88777c256e49292143fc8d2d9aa863

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - typing-extensions
    - python-dateutil
    - elasticsearch >=8.0.0,<9.0.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - elasticsearch_dsl

about:
  home: https://github.com/elasticsearch/elasticsearch-dsl-py
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Higher-level Python client for Elasticsearch
  dev_url: https://github.com/elasticsearch/elasticsearch-dsl-py
  doc_url: https://elasticsearch-dsl.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - miguelgrinberg
    - ezimuel
    - joshmock
    - pquentin
