appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: K9H7Md9QMDEhGR1/hR+pGtpDhXmu3HpQgJlabPQjkAXRQEIWKzbpjJSw//vmV/PhqnbytA87v6fak/u7qkxYMyJ0xEsdDXL4m0wWwYW0Itsxy4BXYfLNzAq+ueCtfA0JAB78zaLhnkzFSSo5uY2OL24yFYB4XjNNLHh8HTI92qIEAHHtesd7nNi08o50sQxwDQmuCdozb9UgVZUftdrMnj0bMQzDhSj1cR2aYSEvAAQW4uV59dlUVpiPL2dJwsxyvao9a3IOd29/gm8X/UAjOfeV1fNKUDfbwUjaD3n3MUBYptS5w8WBkNix7kUWCTSbFJFJFbnQ7kyzcGUz8gHDjGt3exKbf0u/CGJkHeVFT29XOyOhMyFnWagwZrATTb/eG+IIp0dzAtJQhzwn1jZBRVJ1gofQyD38y3i091Wj1qAfqKSWn2bAAcZUiVeJJgiSEfsVfy0uHC/KQJM1AqJGkFxtB946qlbSxJoOS3EjuSjZyctrDtabExSpvdUNTvn+/Ac0/KEsMbI+cQu4QAgINDBOqEWV1KrHlG7nFkfWvpxgxWDlv3j35EpjGBietSOcV0tWiyQkMSiF8T3Ri6Emyo/3GApzBm5+iWEck0UDbXH0oRaDfEoASvBnkSB9tWqLvIRm2vJEfYM229/kJkXZOoRXcn8ehSCMRXuhy5VIsaM=}
